name: runner goreleaser

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Semantic Versioning CLI
        run: |
          npm install -g semver

      - name: Generate Semantic Version Tag
        id: generate_tag
        run: |
          # Fetch the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 --match "v[0-9]*" 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"

          NEXT_TAG=$(semver bump patch "$LATEST_TAG")
          echo "Generated tag: $NEXT_TAG"

          if git rev-parse "$NEXT_TAG" >/dev/null 2>&1; then
            echo "Tag $NEXT_TAG already exists, skipping tag creation"
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag $NEXT_TAG does not exist, will create"
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

          # Expose the tag as an environment variable
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV

      - name: Create Tag
        if: env.TAG_EXISTS == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "$NEXT_TAG" -m "Release $NEXT_TAG"
          git push origin "$NEXT_TAG"

      - name: Run GoReleaser
        if: env.TAG_EXISTS == 'false'
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}